version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - DB_FILE=/app/swift_codes.db
    depends_on:
      - db

  db:
    image: alpine
    command: ["sh", "-c", "mkdir -p /data && tail -f /dev/null"]
    volumes:
      - db-data:/data

volumes:
  db-data:
